spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 45138k9%
  servlet:
    multipart:
      max-file-size: 500MB
mybatis:
  configuration:
    map-underscore-to-camel-case: on # 开启下划线驼峰命名

server:
  port: 8001